# Generated by Django 3.1.2 on 2020-11-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('N', 'New'), ('LR', 'Layout ready'), ('IP', 'In progress'), ('D', 'Done')], default='N', max_length=15)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateField(verbose_name='Deadline')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
