# Generated by Django 3.1.2 on 2021-01-13 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210113_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_name',
            new_name='name',
        ),
    ]
