# Generated by Django 3.1.3 on 2021-01-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order_count',
        ),
    ]
