# Generated by Django 3.1.3 on 2021-01-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_customer_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='desc',
            field=models.TextField(default='default desc', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
